name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ "opened", "reopened", "synchronize", "ready_for_review" ]

jobs:
  guard:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - run: echo "Pipeline started"

  conventional-commits:
    needs: guard
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: guard
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build release with minimal verbosity
        run: dotnet build --no-restore --configuration Release -v m

      - name: Verify code formatting, skip EF migrations, fail on any issues
        run: dotnet format --severity info -v diag --exclude "**/Migrations/**" --verify-no-changes

      - name: Run tests in release mode
        run: dotnet test --no-restore --verbosity normal --configuration Release
